[build]
  command = "pip install --break-system-packages -r requirements-docs.txt && python3 -m mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.11"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
